### ISSUE TITLE
can you add some detail？

### ISSUE THREAD

**Issue by mrlonely001** [599316527/NakeYouku#1]
can you write some detail about how to run this project in your readmefile ?

**Comment by 599316527** [comment]
It's a typical nodejs project. Just run  `npm i` to install dependencies and run `npm run start` which is indicated in the package.json  to run the app.  (NPM & Google Chrome is required.)

**Comment by mrlonely001** [comment]
I run the  `npm run start`  , and get a chrome window ,and I enter a url from youku, then I get nothing ,where can i get the video m3u8 file or something else?

**Comment by 599316527** [comment]
According to your description, your chrome may not meet the requirement of version. Start google-chrome with `--headless` will not launch a visible window.
Headless Chrome is shipping in Chrome [59](https://developers.google.com/web/updates/2017/04/headless-chrome). 

And the app will run a server which provides two APIs:
* List latest 50 videos. POST /grab/list : `cid` is required in body with urlencoded format. 
* Get video's detail: POST /grab/video : `vid` is required in body with urlencoded format. 

Cid which can be found in url `i.youku.com/i/{CID}` standards for channel id.
Vid which can be found in url `v.youku.com/v_show/id_{VID}.html` standards for video id.

Here are request samples

```bash
curl -X POST \
  http://127.0.0.1:8122/grab/list \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d cid=UMzExNjk4MjM0MA%3D%3D

curl -X POST \
  http://127.0.0.1:8122/grab/video \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d vid=XMzIzNDM0NjU4OA%3D%3D
```

**Comment by mrlonely001** [comment]
Thank you a lot . Under your guide, I got an m3u8 file address after I visit the '/grab/video' API with a vid parameter, then I use an m3u8 player to play the address , but after playing about 4 minutes , I got 403 forbidden , and the video got stucked.  Have you ever got this problem ?  
Look forward to your reply.

**Comment by 599316527** [comment]
I believe Youku makes strict limitations, one of which is to overtime the
accessibility, to the real m3u8 address to avoid being referenced by the
thirdparty. One of the solutions is refetch the url again if it is
forbidden. And the retry mechanism of player gives you the  ability to
reload the new m3u8 address automatically.

I made another proxy server to the original clawer api to fetch & cache the
m3u8 content and wrote a little js to enable retry on the web player. Here
is the demo code:
https://gist.github.com/599316527/dece18b74632b34418b64a8d09a94191

Btw. hls is only supported by safari for now. use hls.js to play m3u8 on
chrome.
